export { PawrlyClient, type TransportConfig } from "./client.js";
export type { LocalOptions } from "./transports/local.js";
export { PawrlyError, UnsupportedByTransport } from "./errors.js";
export { QueryHandle, type Row } from "./query.js";
export type {
  CacheEntryInfo,
  CatalogSnapshot,
  ColumnSpec,
  FilterOp,
  FunctionArg,
  FunctionColumn,
  FunctionDescription,
  FunctionInfo,
  HealthReport,
  MaterializeOutcome,
  MaterializeSpec,
  QueryResult,
  RefreshCatalogOutcome,
  RefreshOutcome,
  ReloadReport,
  SchemaSummary,
  SemanticDimension,
  SemanticFilter,
  SemanticMeasure,
  SemanticModelDescription,
  SemanticModelInfo,
  SemanticOrder,
  SemanticQuery,
  SemanticRelationship,
  SemanticSegment,
  SourceDef,
  SourceInfo,
  SourceTestReport,
  TableDescription,
  TableInfo,
  TableName,
  TableSummary,
  VacuumReport,
} from "./result.js";
