"""Transport-agnostic Python client for the Pawrly engine (gRPC + REST)."""

from .client import PawrlyClient
from .errors import PawrlyError, UnsupportedByTransport
from .query import QueryHandle
from .result import (
    CacheEntryInfo,
    CatalogSnapshot,
    ColumnSpec,
    FunctionArg,
    FunctionColumn,
    FunctionDescription,
    FunctionInfo,
    HealthReport,
    MaterializeOutcome,
    MaterializeSpec,
    QueryResult,
    RefreshCatalogOutcome,
    RefreshOutcome,
    ReloadReport,
    SchemaSummary,
    SemanticDimension,
    SemanticFilter,
    SemanticMeasure,
    SemanticModelDescription,
    SemanticModelInfo,
    SemanticOrder,
    SemanticQuery,
    SemanticRelationship,
    SemanticSegment,
    SourceInfo,
    SourceTestReport,
    TableDescription,
    TableInfo,
    TableName,
    TableSummary,
    VacuumReport,
)

__all__ = [
    "PawrlyClient",
    "PawrlyError",
    "UnsupportedByTransport",
    "QueryHandle",
    "QueryResult",
    "HealthReport",
    "MaterializeSpec",
    "MaterializeOutcome",
    "SemanticQuery",
    "SemanticFilter",
    "SemanticOrder",
    "SourceInfo",
    "TableName",
    "TableInfo",
    "ColumnSpec",
    "TableDescription",
    "SchemaSummary",
    "TableSummary",
    "CatalogSnapshot",
    "CacheEntryInfo",
    "FunctionInfo",
    "FunctionArg",
    "FunctionColumn",
    "FunctionDescription",
    "SemanticModelInfo",
    "SemanticModelDescription",
    "SemanticDimension",
    "SemanticMeasure",
    "SemanticRelationship",
    "SemanticSegment",
    "SourceTestReport",
    "ReloadReport",
    "RefreshCatalogOutcome",
    "RefreshOutcome",
    "VacuumReport",
]
