// Generates src/catalog/generated.ts from the repo's curated connector specs
// in sources/{http,file}/*.yaml. Each entry carries display metadata plus the
// full spec YAML, which the connect form templates on Save. Run automatically
// before `dev` / `build` (see package.json). Re-run after editing a spec.
//
// This is intentionally dependency-free (no YAML parser): it scrapes the few
// top-level fields it needs with line regexes and copies the spec verbatim.

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const sourcesDir = join(repoRoot, "sources");
const outFile = join(here, "..", "src", "catalog", "generated.ts");

/** Human label overrides where title-casing the id isn't enough. */
const LABEL_OVERRIDES = {
  github: "GitHub",
  gitlab: "GitLab",
  hackernews: "Hacker News",
  posthog: "PostHog",
  pagerduty: "PagerDuty",
  statusgator: "StatusGator",
  incident_io: "incident.io",
  google_calendar: "Google Calendar",
  stellar_horizon: "Stellar Horizon",
  openai: "OpenAI",
  sendgrid: "SendGrid",
  hubspot: "HubSpot",
  clickup: "ClickUp",
  codex: "Codex CLI",
  claude: "Claude Code",
};

const TOP_KEYS =
  "name|kind|description|wiki|config|examples|tables|variables|cache|safety|raw_table|include|functions|semantic";

function titleCase(id) {
  return id
    .split(/[_-]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function labelFor(id) {
  return LABEL_OVERRIDES[id] ?? titleCase(id);
}

/** Pull the `description:` value, flattening folded/inline scalars to one line. */
function extractDescription(text) {
  const re = new RegExp(
    `^description:\\s*([>|])?\\s*([\\s\\S]*?)(?=^(?:${TOP_KEYS}):)`,
    "m",
  );
  const m = text.match(re);
  if (!m) return "";
  const body = m[2] ?? "";
  const flat = body.replace(/\s+/g, " ").trim();
  return flat.length > 160 ? flat.slice(0, 157) + "…" : flat;
}

function firstMatch(text, re) {
  const m = text.match(re);
  return m ? m[1] : undefined;
}

function buildEntries(kindDir, category) {
  const dir = join(sourcesDir, kindDir);
  let files;
  try {
    files = readdirSync(dir).filter((f) => /\.ya?ml$/.test(f));
  } catch {
    return [];
  }
  const entries = [];
  for (const file of files) {
    const yaml = readFileSync(join(dir, file), "utf8");
    const id = basename(file).replace(/\.ya?ml$/, "");
    const kind = firstMatch(yaml, /^kind:\s*(\S+)/m) ?? "http";
    const secretVar = firstMatch(yaml, /\$\{secret:([A-Za-z0-9_]+)\}/);
    const docsUrl =
      firstMatch(yaml, /^#\s*Reference:\s*(\S+)/m) ??
      firstMatch(yaml, /^#.*?(https?:\/\/\S+)/m);
    entries.push({
      id,
      label: labelFor(id),
      kind,
      category,
      description: extractDescription(yaml),
      secretVar,
      docsUrl,
      yaml,
    });
  }
  entries.sort((a, b) => a.label.localeCompare(b.label));
  return entries;
}

const connectors = [
  ...buildEntries("http", "api"),
  ...buildEntries("file", "database"),
];

const header = `// AUTO-GENERATED by scripts/build-catalog.mjs — do not edit by hand.
// Regenerated before \`pnpm dev\` / \`pnpm build\`. Source: repo sources/{http,file}/*.yaml.

export interface GeneratedConnector {
  id: string;
  label: string;
  /** Source kind string (e.g. "http", "file"). */
  kind: string;
  category: "api" | "database";
  description: string;
  /** The \${secret:NAME} variable the spec references, if any. */
  secretVar?: string;
  docsUrl?: string;
  /** Full curated spec, templated on Save. */
  yaml: string;
}

export const GENERATED_CONNECTORS: GeneratedConnector[] =
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, header + JSON.stringify(connectors, null, 2) + ";\n");
console.log(
  `build-catalog: wrote ${connectors.length} connectors → ${outFile}`,
);
