//! Subcommand implementations.

pub mod cache;
pub mod check;
pub mod config;
pub mod console;
pub mod format;
pub mod function;
pub mod init;
pub mod materialize;
pub mod mcp_http;
pub mod mcp_stdio;
pub mod schema;
pub mod semantic;
pub mod serve;
pub mod source;
pub mod sql;
pub mod status;
pub mod stop;
pub mod uninstall;
pub mod update;
pub mod validate;
